name: run-tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.5, 8.4, 8.3, 8.2]
        laravel: ["11.*", "12.*"]
        db: [mysql, sqlite, pgsql]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: ^9.10
          - laravel: 12.*
            testbench: ^10.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - DB ${{ matrix.db }} - ${{ matrix.dependency-version }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_USER: protone_media_db_test
          MYSQL_DATABASE: protone_media_db_test
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: protone_media_db_test
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: protone_media_db_test
        ports:
          - 5432
        options: --health-cmd="pg_isready -U protone_media_db_test" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, mysqli, pdo_mysql, pgsql, pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests (MySQL)
        run: vendor/bin/phpunit
        if: ${{ matrix.db == 'mysql' }}
        env:
          DB_DATABASE: protone_media_db_test
          DB_USERNAME: protone_media_db_test
          DB_PASSWORD: secret
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Execute tests (SQLite)
        run: vendor/bin/phpunit
        if: ${{ matrix.db == 'sqlite' }}
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Execute tests (PostgreSQL)
        run: vendor/bin/phpunit
        if: ${{ matrix.db == 'pgsql' }}
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: protone_media_db_test
          DB_USERNAME: protone_media_db_test
          DB_PASSWORD: secret
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
